
(() => {
  const qs=(s,c=document)=>c.querySelector(s); const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
  const search=qs('#searchInput'); const searchSummary=qs('#searchSummary');
  function typeset(el){ if(window.MathJax?.typesetPromise){ MathJax.typesetPromise(el?[el]:undefined).catch(()=>{}); } }
  window.switchTab=function(tabId,btn){ qsa('.tab-pane').forEach(x=>x.classList.remove('active')); qsa('.tab-btn').forEach(x=>x.classList.remove('active')); qs('#'+tabId)?.classList.add('active'); (btn||event?.currentTarget)?.classList.add('active'); const isT=tabId==='tab-tst'; qs('#sidebar-danang').style.display=isT?'none':'block'; qs('#sidebar-tst').style.display=isT?'block':'none'; qs('#tstFilterPills').style.display=isT?'flex':'none'; search.value=''; clearSearch(); window.scrollTo({top:220,behavior:'smooth'}); };
  window.toggleSolution=function(btn){const content=btn.nextElementSibling; const open=getComputedStyle(content).display!=='none'; content.style.display=open?'none':'block'; btn.textContent=open?'👁️ Xem lời giải & Thang điểm':'🙈 Ẩn lời giải & Thang điểm'; if(!open)typeset(content)};
  window.copyText=function(btn){const card=btn.closest('.problem-item'); const id=card.querySelector('.problem-id span:first-child')?.innerText||'Bài toán'; const content=card.querySelector('.problem-content')?.innerText||card.innerText; navigator.clipboard.writeText(`${id}:\n${content}`).then(()=>{const old=btn.textContent;btn.textContent='✅ Đã sao chép';setTimeout(()=>btn.textContent=old,1500)})};
  function norm(s){return (s||'').toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d')}
  function clearSearch(){qsa('.hidden-by-search').forEach(x=>x.classList.remove('hidden-by-search')); searchSummary.classList.remove('visible'); searchSummary.textContent='';}
  function searchBook(val){let matches=0; qsa('#tab-danang .chapter-block').forEach(ch=>{let any=false; const subs=qsa('.book-subsection',ch); if(!subs.length){const hit=norm(ch.textContent).includes(val); ch.classList.toggle('hidden-by-search',!hit); if(hit){matches++;any=true} return;} subs.forEach(sub=>{const hit=norm(sub.textContent).includes(val); sub.classList.toggle('hidden-by-search',!hit); if(hit){matches++;any=true}}); const headText=norm(ch.querySelector('.chapter-heading')?.textContent||''); if(headText.includes(val)){subs.forEach(s=>s.classList.remove('hidden-by-search')); any=true; matches=Math.max(matches,1)} ch.classList.toggle('hidden-by-search',!any)}); return matches;}
  function searchTst(val){let matches=0; qsa('#tab-tst .exam-card').forEach(card=>{const hit=norm((card.dataset.search||'')+' '+card.innerText).includes(val); card.classList.toggle('hidden-by-search',!hit); if(hit)matches++}); return matches;}
  function applySearch(){const raw=search.value.trim(); if(!raw){clearSearch();return} const val=norm(raw); const active=qs('.tab-pane.active'); const n=active?.id==='tab-tst'?searchTst(val):searchBook(val); searchSummary.textContent=`Tìm thấy ${n} mục phù hợp với “${raw}”.`; searchSummary.classList.add('visible')}
  search?.addEventListener('input',applySearch);
  qsa('#tstFilterPills .pill').forEach(p=>p.addEventListener('click',()=>{qsa('#tstFilterPills .pill').forEach(x=>x.classList.remove('active'));p.classList.add('active');const f=p.dataset.filter;qsa('#tab-tst .exam-card').forEach(card=>card.classList.toggle('hidden-by-search',!(f==='ALL'||card.dataset.filter===f)));}));
  qsa('.solution-toggle').forEach(btn=>btn.addEventListener('click',()=>{const sol=btn.nextElementSibling; const collapsed=sol.classList.toggle('is-collapsed'); btn.textContent=collapsed?'Hiện lời giải':'Ẩn lời giải';btn.setAttribute('aria-expanded',String(!collapsed)); if(!collapsed)typeset(sol)}));
  const allBtn=qs('#toggleAllSolutions'); let allShown=true; allBtn?.addEventListener('click',()=>{allShown=!allShown;qsa('.example-solution').forEach(s=>s.classList.toggle('is-collapsed',!allShown));qsa('.solution-toggle').forEach(b=>{b.textContent=allShown?'Ẩn lời giải':'Hiện lời giải';b.setAttribute('aria-expanded',String(allShown))});allBtn.textContent=allShown?'🙈 Ẩn toàn bộ lời giải mẫu':'👁️ Hiện toàn bộ lời giải mẫu'; if(allShown)typeset(qs('#book-content'))});
  const theme=qs('#themeToggle'); const saved=localStorage.getItem('vmo-theme'); if(saved==='dark'){document.body.classList.add('dark');theme.textContent='☀️'} theme?.addEventListener('click',()=>{document.body.classList.toggle('dark');const d=document.body.classList.contains('dark');theme.textContent=d?'☀️':'🌙';localStorage.setItem('vmo-theme',d?'dark':'light')});
  const top=qs('#backToTop'); addEventListener('scroll',()=>top.classList.toggle('visible',scrollY>700),{passive:true}); top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
  const links=qsa('#sidebar-danang a[href^="#"]'); const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active-link',a.getAttribute('href')==='#'+e.target.id))}})},{rootMargin:'-25% 0px -65% 0px'}); qsa('#book-content h1[id],#book-content h2[id]').forEach(h=>obs.observe(h));
})();
